#!/bin/env python3
import os
from pathlib import Path
import smtplib
import time
from typing import List

import details

"""
This is intended to run regularly via chron job on my raspberry pi.
It sends me an email from an outlook account every run analysing and listing 
all the changed files in the last 7 days. It's intended to run this at midnight
once a week right after running `all-repos-clone` as well. `

Create a file called details.py with the following layout:
username = <email address>
password = <email password>
recieve_email = <email address>
"""

# Root directory of hard drive
DIRPATH = Path("/mnt/PiShare/")
DAYS = 7


def getChangedFiles() -> List[str]:
    changedFiles: List[str] = []
    files = list(DIRPATH.rglob("*"))

    for file in files:
        timedelta = time.time() - os.path.getmtime(file)
        timedelta /= 60 * 60 * 24

        if ".git" in str(file) or str(file.stem)[0] == "." or file.is_dir():
            continue

        if timedelta < DAYS:
            changedFiles.append(str(file))

    return changedFiles


def notifyOwner(changedFiles: List[str]):
    # Sends email from an outlook account
    server = smtplib.SMTP("smtp.office365.com:587")
    server.ehlo()
    server.starttls()
    server.login(details.username, details.password)

    message = f"Subject: PiShare Weekly Update\n\nUpdated files: ({len(changedFiles)}):\n" + '\n'.join(changedFiles) + "\n\n" + ("Backup Recommended\nsudo mount /dev/sda2 /mnt/Elements && sudo rsync /mnt/PiShare/ /mnt/Elements --progress -zvrutU" if len(changedFiles) > 5 else '')

    server.sendmail(details.username, details.recieve_email, message)
    server.quit()


def main() -> int:
    changedFiles: List[str] = getChangedFiles()
    notifyOwner(changedFiles)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
