#!/bin/bash

set -xe

wallpaper_dir="$HOME/.wallpapers"
wallpapers=("$wallpaper_dir"/*)
random_wallpaper="${wallpapers[RANDOM % ${#wallpapers[@]}]}"

gsettings set org.gnome.desktop.background picture-uri "file://$random_wallpaper"
gsettings set org.gnome.desktop.background picture-uri-dark "file://$random_wallpaper"
